apiVersion: xl/v2
kind: Blueprint
metadata:
  name: XL OP
  description: |
    This blueprint deploys DAI Deploy operator, DAI Release operator, and XL-k8s-foundation into an existing Kubernetes installation (local single-node Kubernetes, on-premises multi-node Kubernetes cluster, Google Kubernetes Engine cluster, or Amazon EKS cluster).
  author: digitalai
  version: 1.0
spec:
  parameters:
    - name: K8sSetup
      type: Select
      prompt: "Select the Kubernetes setup where the digitalai Devops Platform will be installed, updated or cleaned:"
      options:
        - label: Openshift
          value: Openshift
        - label: AWS EKS
          value: AWSEKS
        - label: Plain multi-node K8s cluster
          value: PlainK8s
        - label: Azure AKS
          value: AzureAKS
        - label: Google Kubernetes Engine
          value: GoogleGKE
      saveInXlvals: true
      description: "The flavour of Kubernetes to deploy or undeploy the digitalai Devops Platform to. Only the listed options are supported."

    - name: OsType
      type: Input
      prompt: "The type of operating system where the xl command is running:"
      value: !expr "os('_operatingsystem')"
      saveInXlvals: true
      ignoreIfSkipped: true

    - name: ProcessType
      type: Input
      overrideDefault: true
      prompt: "The type of process command is running:"
      saveInXlvals: true

    - name: UseCustomNamespace
      type: Confirm
      default: true
      saveInXlvals: true
      prompt: "Do you want to use an custom Kubernetes namespace (current default is 'digitalai'):"
      description: "Type yes to use an already existing namespace, not 'digitalai', in your kubernetes cluster for doing an install, update or clean of the Xebialabs Devops Platform."

    - name: Namespace
      type: Input
      promptIf: !expr "UseCustomNamespace"
      prompt: "Enter the name of the existing Kubernetes namespace where the XebiaLabs DevOps Platform will be installed, updated or cleaned:"
      default: digitalai
      saveInXlvals: true
      ignoreIfSkipped: true
      description: "Type the name of the existing Kubernetes namespace to install, update or clean the XebiaLabs Devops Platform."

    - name: ServerType
      type: Select
      prompt: "Product server you want to perform upgrade for:"
      options:
        - label: Digital.ai Release
          value: dai-release
        - label: Digital.ai Deploy
          value: dai-deploy
      saveInXlvals: true
      description: Select product server you want to perform upgrade for.

    - name: ShortServerName
      type: Input
      saveInXlvals: true
      value: !expr "ServerType == 'dai-release' ? 'xlr' : 'xld'"
      description: Short product server used for filtering in the blueprints.

    - name: GenerationDateTime
      type: Input
      saveInXlvals: true
      value: !expr "os('_datetime')"
      description: Generation date and time.

  files: []
