apiVersion: xl/v2
kind: Blueprint
metadata:
  name: XL OP
  description: |
    This blueprint deploys DAI Deploy operator, DAI Release operator, and XL-k8s-foundation into an existing Kubernetes installation (local single-node Kubernetes, on-premises multi-node Kubernetes cluster, Google Kubernetes Engine cluster, or Amazon EKS cluster).
  author: digitalai
  version: 1.0
spec:
  parameters:
    - name: K8sSetup
      type: Select
      prompt: "Select the Kubernetes setup where the digitalai Devops Platform will be installed or uninstalled:"
      options:
        - label: Openshift
          value: Openshift
        - label: AWS EKS
          value: AwsEKS
        - label: Plain multi-node K8s cluster
          value: PlainK8SCluster
        - label: Azure AKS
          value: AzureAKS
        - label: Google Kubernetes Engine
          value: GoogleGKE
      saveInXlvals: true
      description: "The flavour of Kubernetes to deploy or undeploy the digitalai Devops Platform to. Only the listed options are supported"

    - name: OsType
      type: Input
      prompt: "The type of operating system where the xl command is running:"
      value: !expr "os('_operatingsystem')"
      saveInXlvals: true
      ignoreIfSkipped: true

    - name: ProcessType
      type: Input
      overrideDefault: true
      prompt: "The type of process command is running:"
      saveInXlvals: true

    - name: UseCustomNamespace
      type: Confirm
      default: true
      saveInXlvals: true
      prompt: "Do you want to use an custom Kubernetes namespace (current default is 'digitalai')?"
      description: "Use an already existing namespace in your kubernetes cluster for doing an upgrade of the Xebialabs Devops Platform."

    - name: Namespace
      type: Input
      promptIf: !expr "UseCustomNamespace"
      prompt: "Enter the name of the existing Kubernetes namespace where the XebiaLabs DevOps Platform will be installed, updated or undeployed:"
      default: digitalai
      saveInXlvals: true
      ignoreIfSkipped: true
      description: "The existing Kubernetes namespace to install, update or undeploy the XebiaLabs Devops Platform "
  files: []
