apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: xld-operator-manager-role
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - "*"
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
- apiGroups:
  - xld.digital.ai
  resources:
  - digitalaideploys
  - digitalaideploys/status
  - digitalaideploys/finalizers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- verbs:
  - "*"
  apiGroups:
  - "rbac.authorization.k8s.io"
  resources:
  - "clusterrolebindings"
  - "clusterroles"
- verbs:
  - "*"
  apiGroups:
  - "apps"
  resources:
  - "deployments"
  - "statefulsets"
  - "daemonsets"
- verbs:
  - "*"
  apiGroups:
  - "networking.k8s.io"
  resources:
  - "ingresses"
- verbs:
  - "*"
  apiGroups:
  - ""
  resources:
  - "configmaps"
  - "persistentvolumeclaims"
  - "secrets"
  - "serviceaccounts"
  - "services"
- verbs:
  - "*"
  apiGroups:
  - "rbac.authorization.k8s.io"
  resources:
  - "rolebindings"
  - "roles"
- apiGroups:
  - policy
  resources:
  - poddisruptionbudgets
  verbs:
  - '*'

#+kubebuilder:scaffold:rules
