apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: xlr-operator-manager
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
- apiGroups:
  - ""
  resources:
  - "configmaps"
  - "persistentvolumeclaims"
  - "secrets"
  - "serviceaccounts"
  - "services"
  verbs:
  - "*"
- apiGroups:
  - "apps"
  resources:
  - "deployments"
  - "statefulsets"
  - "daemonsets"
  verbs:
  - "*"
- apiGroups:
  - "batch"
  resources:
  - "jobs"
  verbs:
  - "create"
  - "delete"
  - "get"
  - "list"
- apiGroups:
  - "networking.k8s.io"
  resources:
  - "ingresses"
  verbs:
  - "*"
- apiGroups:
  - policy
  resources:
  - poddisruptionbudgets
  verbs:
  - '*'
- apiGroups:
  - "rbac.authorization.k8s.io"
  resources:
  - "rolebindings"
  - "roles"
  verbs:
  - "*"
- apiGroups:
  - xlr.digital.ai
  resources:
  - digitalaireleases
  - digitalaireleases/status
  - digitalaireleases/finalizers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
